services:
  postgres:
    image: postgres:15
    container_name: blueprint-postgres
    environment:
      POSTGRES_DB: prblueprint
      POSTGRES_USER: blueprint
      POSTGRES_PASSWORD: 1234 
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: blueprint-redis
    ports:
     - "6379:6379"
     

volumes:
  postgres-data: 